version: 2
jobs:
  build-nsmd:
    working_directory: /go/src/github.com/networkservicemesh/networkservicemesh/
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            export COMMIT="${CIRCLE_SHA1:8:8}"
            export TAG="${COMMIT}"
            make docker-nsmd-build
            make docker-nsmd-push
  build-nsmd-k8s:
    working_directory: /go/src/github.com/networkservicemesh/networkservicemesh/
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - setup_remote_docker:
            ./scripts/go-mod-download.sh
            make aws-start
          no_output_timeout: 40m
      - save_cache:
          key: cncf-data-aws-<< parameters.cluster_id >>-{{.Environment.CIRCLE_WORKFLOW_ID}}
          paths:
            - data
            - scripts/aws
            - ~/.aws
            - ~/.kube
      - run:
          when: on_fail
          no_output_timeout: 40m
          command: |
            export NSM_AWS_SERVICE_SUFFIX="-<< parameters.cluster_id >>-${CIRCLE_WORKFLOW_ID}"
            make aws-destroy
    environment:
      CLUSTER_ID: "<< parameters.cluster_id >>"
      KUBECONFIG: /home/circleci/project/data/kubeconfig
      GO111MODULE: "on"

